#pragma once
#define RGB_DI_PIN B0
#define DRIVER_LED_TOTAL 34
#define RGB_MATRIX_SPLIT {17,17}
#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
