#include "waffle.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [_BASE] = LAYOUT_split_bar(
    STAR, ALTQ, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, ALTP, KC_NO, KC_MPLY,
    QMKTD, SFA, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, SFCLN, KC_MNXT,
    CP_PSTE, CTLZ, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, CTLDOT, KC_UP, KC_MPRV,
    KC_NO, KC_NO, KC_LGUI, LWRSPC, KC_BSPC, CLIPST, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT
  ),
  [_LOWER] = LAYOUT_split_bar(
    HAP, ALT1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, ALT0, KC_NO, KC_NO,
    DOCSTD, SFEXM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, SFPRN, KC_NO,
    OUT, CTLESC, KC_TAB, KC_CAPS, KC_TILD, KC_GRV, KC_LEFT, KC_DOWN, KC_UP, CTLRGHT, KC_NO,
    KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
  )
};
