#pragma once
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#ifdef RGBLIGHT_ENABLE
#define RGBLIGHT_ANIMATIONS
#define RGBLIGHT_SLEEP
#define RGBLIGHT_HUE_STEP 5
#define RGBLIGHT_SAT_STEP 5
#endif
