#pragma once
#define RGBLIGHT_LIMIT_VAL 200
#define RGBLIGHT_ANIMATIONS
#undef RGBLED_NUM
#define RGBLED_NUM 42
#undef RGBLED_SPLIT
#define RGBLED_SPLIT { 21, 21 }
#undef RGBLIGHT_HUE_STEP
#define RGBLIGHT_HUE_STEP 5
#undef RGBLIGHT_SAT_STEP
#define RGBLIGHT_SAT_STEP 5
#undef RGBLIGHT_VAL_STEP
#define RGBLIGHT_VAL_STEP 5
#define RGBLIGHT_SLEEP
