#pragma once
#define RGBLIGHT_LIMIT_VAL 200
#define RGBLIGHT_MODE_STATIC_GRADIENT
#define RGBLIGHT_MODE_TWINKLE
#undef RGBLED_NUM
#define RGBLED_NUM 42
#undef RGBLED_SPLIT
#define RGBLED_SPLIT { 21, 21 }
#define RGBLIGHT_SLEEP
